DROP TABLE IF EXISTS "books";
CREATE TABLE "books" (
  "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "ISBN" VARCHAR(32) NOT NULL,
  "TITLE" VARCHAR(1024),
  "AUTHOR" VARCHAR(512),
  "PUBLICATION_YEAR" INT,
  "UAH" DECIMAL(13,2),
  "EUR" DECIMAL(13,2),
  "DELETED" BOOLEAN DEFAULT FALSE
);

-- unique constraint enforced at application level to allow soft-delete reuse of ISBN

DROP TABLE IF EXISTS "rates";
CREATE TABLE "rates" (
  "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "DATE" TIMESTAMP,
  "RATE" DECIMAL(13,2)
);
